apiVersion: 1

datasources:
  # Prometheus - Métricas de Kafka via Kafka Exporter
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  # PostgreSQL - Base de datos de eventos y alertas
  - name: Smart City PostgreSQL
    type: postgres
    access: proxy
    url: ${PGHOST}:5432
    database: ${PGDATABASE}
    user: ${PGUSER}
    isDefault: false
    editable: true
    secureJsonData:
      password: ${PGPASSWORD}
    jsonData:
      sslmode: 'require'
      postgresVersion: 1500
      timescaledb: false

  # Elasticsearch - Logs y eventos
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: false
    editable: true
    jsonData:
      esVersion: "8.0.0"
      timeField: "timestamp"
      logMessageField: "message"
      logLevelField: "severity"
